### ISSUE TITLE
chai3d 1.6.2 no longer available

### ISSUE THREAD

**Issue by sensestage** [radarsat1/dimple#1]
This url
http://chai3d.org/files/build-1-6-2/chai3d-1.6.2-win32.zip
is no longer working.

http://chai3d.org/download/releases only lists versions 2.0 and up.

**Comment by radarsat1** [comment]
Hi, probably the right thing to do is simply update Dimple for CHAI 3.0.0.  I think this can be done without too much trouble, but it's not _completely_ trivial.  I may get a chance to do it in the near future.  They say a github repository is also forthcoming, which presumably will include previous versions.  In the meantime, I do have the zip, or my personal git repository (with the "dimple" branch) could be made to work:  https://github.com/radarsat1/chai3d/tree/dimple

**Comment by sensestage** [comment]
ok, thanks! I'll try that.
Maybe I also look into a method to compile dimple without the chai3d for usecases where the interaction with these haptic devices is not needed.

**Comment by radarsat1** [comment]
Major progress on updating to CHAI 3.2 just pushed to master.  It still needs some work to verify with haptic devices, but it builds against the latest CHAI now and simple graphical tests appear to succeed. It will probably only work on Linux until I can fix some library linking issues, but it's just path detection stuff and detecting which libraries CHAI needs for its device drivers. So still some work to do. @bbattey it's probably too early to *really* test, probabiy won't link successfully on OS X yet, but it's a big step.
