### ISSUE TITLE
Grab to object -- too soft?

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#13]
It would be ideal to be able to adjust the stiffness of the (presumed) spring between device and the object we grab. Sometimes it feels exceedingly soft. (Using Falcon)

**Comment by radarsat1** [comment]
Indeed, these are hard coded in [PhysicsSim.cpp](https://github.com/radarsat1/dimple/blob/master/src/PhysicsSim.cpp#L212) in case you want to try messing with them.  They could be made into variables, we would need an appropriate name for the "grab" spring.  Should it be in /world?

**Comment by bbattey** [comment]
At I first blush, I assume such variables would be in /world, since it seems like all else is. But it is in a sense out of the world, in which case something like  /connection/<parameter> might make sense. Looking in PhysicsSim.cpp, the only items I see are force.mul and force.addScaler , Looking at the current Chai version of 01-ODE-Cube and 01-3dSpring, it also is not clear to me how the connection parameters are controlled -- but they certainly provide a very firm connection.

**Comment by radarsat1** [comment]
Grab spring parameters now controllable in 13e1ca5455bf98cd94fd34dbe919653ee161bb51
