### ISSUE TITLE
Update of liblo version needed

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#14]
The bootstrap file references liblo-0.28, but this was generating a compile error for me (Max OSX):

error: absolute value function 'abs' given an argument of
      type 'long' but has parameter of type 'int' 

I had to set the bootstrap to use version 0.29 instead.

Note that for both 0.28 and 0.29, I had to comment out the checksum test, since it persistently failed.

**Comment by radarsat1** [comment]
Fixed in 294573baac5952773eff83be58abadca8366622f

**Comment by radarsat1** [comment]
Re-open if you still have problems compiling it.

**Comment by bbattey** [comment]
Yes, this part works now.

**Comment by bbattey** [comment]
Or, to be more precise, it found the liblo successfully, though then generated an error (unspecified) in the compiling of ODE. A second run also was successful at compiling ODE, but, of course, trips up on trying to find the chai3D library v1.62.
