### ISSUE TITLE
Destroy of constrained object bombs

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#16]
I haven't tried the script directly, but recreating the sequence in destroy.sh in Max, I found that the step /world/s2/destroy caused Dimple to bomb.

**Comment by radarsat1** [comment]
Hm, the script doesn't crash Dimple for me, it works as expected.  In a0b83470d70125729869c532247c2c9fdb9ec106 I fixed a pretty important bug related to paths which could affect random things like this, maybe try master now and see if it is fixed.

**Comment by bbattey** [comment]
Unfortunately, because of the bugs I noticed in OSX compile and the unavailable reference to the legacy version of CHAI3D, I haven't been able to successfully compile on my machine, so I would need access to a new Mac binary to test.

**Comment by radarsat1** [comment]
Considering this fixed after a lot of testing.
