### ISSUE TITLE
compiling on OSX

### ISSUE THREAD

**Issue by malloch** [radarsat1/dimple#2]
It seems that compiling DIMPLE on OSX generates a couple of errors:

Simulation.cpp:708:23: error: use of undeclared identifier ‘CLOCK_REALTIME'
Simulation.cpp:726:21: error: use of undeclared identifier 'sem_timedwait'

**Comment by radarsat1** [comment]
Hopefully fixed in e1012a834c1ca8a229e43359f98b1a5349eca989, need to test on OS X

**Comment by MathiasKirkegaard92** [comment]
I am having issues with compiling DIMPLE on OSX. 

I had to change paths for OpenGl and GLUT in configure.ac, to succeed with generating makefiles.  I did this by adding the prefix:

`DEV_PREFIX="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"`

Alternatively one could run the command: 
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

But when compiling i get this error with version 10.14 of OSX: 

`Simulation.cpp:725:20: error: no matching constructor for initialization of 'std::thread'
        m_thread = std::thread(Simulation::run, this)`
