### ISSUE TITLE
Create Mesh doesn't work properly

### ISSUE THREAD

**Issue by MarviB16** [radarsat1/dimple#23]
Hello,

we are currently trying to get a custom mesh working in DIMPLE. We tried the example in the /test/test.pd file, called meshtest. But it doesn't work. Neither the cup.obj nor the cylinder.3ds meshes appear.

We use the following objects:
send /world/mesh/create test cylinder.3ds
send /world/test/size 1
send /world/test/position 0 0 -0.2

Also we can't get the textures to work in the marbles example.

We use DIMPLE RC 0.1.0, but the test/test.pg file from DIMPLE 0.0.9

**Comment by radarsat1** [comment]
cup.obj isn't anywhere, I removed it from the new test.pd.  I have tested with cylinder.3ds though, it should work.  I think you need to give it an initial position,

> send /world/mesh/create test cylinder.3ds 0 0 0

if it doesn't load try using an absolute path.

**Comment by MarviB16** [comment]
Works, but only with an absolute path.

**Comment by radarsat1** [comment]
Ah, excellent. :)  It's probably to do with the "working directory" of Dimple, I think the path in there expects Dimple to have been executed from the "src" directory, but if you double-clicked Dimple it will differ. Not sure how to fix that to be honest !
