### ISSUE TITLE
How to color objects?

### ISSUE THREAD

**Issue by MarviB16** [radarsat1/dimple#25]
Hello,

I am currently trying to color a stick I made in dimple. The stick was created like this:

oscformat /world/prism/create stick 0.2 0 0.3

and I want to color it by calling

oscformat  /world/stick/color r g b 

for r,g and b I tried (255, 255, 255) and (1, 1, 1) as well as (0, 0 ,0)

but it is still grey not white or black. What am I doing wrong? I tried the "grab tutorial" were the sphere should be colored too, but it isn't.
Thanks!

**Comment by radarsat1** [comment]
Hi, I just tested it and colours seem to work fine.  (0--1 is the correct RGB range) In the grab example only the object `box_proxy` received a color command.

Maybe you are not sending the message you think you are sending? At least in PureData, the `oscformat` object takes the message address as its only argument.  For the other arguments you have to send a message to it.

So the patch that sets `box_proxy`'s colour looks like this:

```
[0.7 0.4 0.2(
|
[oscformat /world/box_proxy/color]
|
[s osc]
```

**Comment by MarviB16** [comment]
Okay, 
i found the "bug", maybe i shouldn't use , but . 

So solved thanks. ;-)
