### ISSUE TITLE
MacOS + Falcon: Falcon failing to load

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#4]
On Mac OS (10.11) I am finding that Dimple fails on the firmware upload to the Falcon. I am having to use the help file for the np_nifalcon-1.5 object in Max to load the firmware. Once that is done, Dimple starts up fine.

**Comment by radarsat1** [comment]
This was always difficult but it's good to know it works reliably in at least one implementation.  Leaving open as a bug for now.

**Comment by radarsat1** [comment]
Does this still occur for you?
I have increased the timeout for device initialization to take into account firmware download in 93b9075ad0e434b5a802ed19c68891dee9a14370

**Comment by radarsat1** [comment]
We verified together in person that the Falcon now starts up correctly, so closing.
