### ISSUE TITLE
External paths not working (w/OSX in particular?)

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#6]
The examples that address external texture or 3D object files don't work in OSX. Do they elsewhere? I've tried a variety of solutions: opening the contents of the .app and placing files there, assuming the binary's location is the default URL; providing fully qualified path names from root; using ~ account paths, etc.

**Comment by radarsat1** [comment]
I couldn't find any code in dimple related to textures.  I'm sure it was implemented at one point but probably on some lost branch.  I'll leave this open in case I can get my hands on it or reimplement it at some point.

**Comment by radarsat1** [comment]
Texture loading functionality restored in f8194135ddc7955bf02e0c3a45c52ea23889cbb5
