### ISSUE TITLE
Some force or force/magnitude queries not working

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#7]
test.pd / force stick
------
/world/c1/force/magnitude/get, which references the hinge, is not returning any data, nor is stiffness.

This does work, however:
/world/stick/force/get

test.pd / snake
----

As with force stick, get on ../hinge[x]/force/ or /force/magnitude returns nothing  from DIMPLE

test.pd / s3 accel
----
Again,  the magnitude query does not work

**Comment by radarsat1** [comment]
Should be fixed by 3590da54770da3273e9af766a1f30b418a9124e6
