### ISSUE TITLE
velocity/magnitude returning 0

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#8]
test.pd / snake
---

/world/sn[x]/velocity/magnitude/get   100 is resulting in matching messages coming back from DIMPLE, but the value   consistently reads 0. regardless of the motion of the prisms. 

On the other   hand /world/sn1/velocity/get 100 works, returning the 3-number magnitude

**Comment by radarsat1** [comment]
Duplicate of #7?

**Comment by bbattey** [comment]
Slightly different, I think. In #7, no data is returned. In this example, data is returned, but it is always 0.

**Comment by radarsat1** [comment]
Fixed in 3590da54770da3273e9af766a1f30b418a9124e6
