### ISSUE TITLE
Missing cup.obj + conflict re .3ds and .obj

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#9]
test.pd meshtest 

calls for creating a mesh on a cup.obj file. This file doesn't exist in the   dimple release. Should it? 

Messages.txt in 'Creating Objects' only indicates .3ds as an extension and said meshes must be specified in the .3ds format.  I think this is an error, and .obj files are also allowed (?)

**Comment by radarsat1** [comment]
Don't know where that file went but at least the code for meshes still seems to be there.  Maybe it can be replaced with a different example file.

**Comment by radarsat1** [comment]
Fix meshtest in test.pd to load cylinder.3ds instead of cup.obj: eb4548a9c2abcf0642319718ad0d4fd968928124
File formats documented in eae343218e294b53a6061012da31830d8a5a65d6.

Documentation still needs more general updating but these points are addressed now, so closing.
